  name: Test
  on:
    push:
      branches:
        - main
  jobs:
    build:
      runs-on: ubuntu-latest

      steps:

        - name: Access Secrets
          run : |
            echo "API_KEY : ${{secrets.API_KEY}}" >> .env